In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/Master_2023_sept/COGMEN-main

/content/drive/MyDrive/Master_2023_sept/COGMEN-main


In [3]:

!pip3 install torch torchvision #--use-deprecated=legacy-resolver
!pip3 install torchaudio #--use-deprecated=legacy-resolver
!pip3 install -U torch_geometric #--use-deprecated=legacy-resolver
!pip3 install comet_ml #--upgrade --quiet --use-deprecated=legacy-resolver
!pip3 install -U sentence-transformers #--use-deprecated=legacy-resolver

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 28.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.3/687.3 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.1/979.1 kB 45.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 68.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.9/137.9 kB 11.1 MB/s eta 0:00:00
  Attempting uninstall: python-box
    Found existing installation: python-box 7.2.0
    Uninstalling python-box-7.2.0:
      Successfully uninstalled python-box-7.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 5.8 MB/s eta 0:00:00


In [ ]:
!python eval_FP8_mil.py --dataset="iemocap_4" --modalities="atv"

2024-08-30 22:22:46.030909: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-30 22:22:46.050702: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-30 22:22:46.056836: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-30 22:22:47.309116: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
comet_ml is installed but `COMET_API_KEY` is not set.
/content/drive/MyDrive/Master_2023_sept/COGMEN-main/eval_FP8_mil.py:81: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the def

In [ ]:
!python eval_bin_mil.py --dataset="iemocap_4" --modalities="atv"

2024-08-30 22:09:54.117340: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-30 22:09:54.138357: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-30 22:09:54.144264: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-30 22:09:54.158546: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-30 22:09:55.392170: W tensorflow/compiler/tf2

In [ ]:
!python eval_bin_svi.py --dataset="iemocap_4" --modalities="atv"

2024-08-30 22:10:18.394442: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-30 22:10:18.415052: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-30 22:10:18.421028: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-30 22:10:18.435025: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-30 22:10:19.669564: W tensorflow/compiler/tf2

In [ ]:
!python eval_FP8_svi.py --dataset="iemocap_4" --modalities="atv"

2024-08-30 22:10:45.429215: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-30 22:10:45.451157: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-30 22:10:45.457329: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-08-30 22:10:45.472867: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-08-30 22:10:46.717980: W tensorflow/compiler/tf2

In [8]:
import torch
import torch.nn as nn
import numpy as np
!pip3 install torch-geometric<2.2.0
import torch_geometric

/bin/bash: line 1: 2.2.0: No such file or directory


In [9]:
model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/trained_model3.pt')

<ipython-input-9-abc098b37b9e>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/trained_model3.pt')


ModuleNotFoundError: No module named 'torch_geometric.nn.conv.utils.inspector'

In [ ]:
weights1=[]
bias1=[]
def get_wb(model):
    for name, param in model.named_parameters():
        if 'weight' in name:
            print(f'Weight matrix for {name}:')
            print(param)
            weights1.append(param.view(-1))
        elif 'bias' in name:
            print(f'Bias vector for {name}:')
            print(param)
            bias1.append(param.view(-1))
    # print(weights_and_biases_vector)
    weights_vec=torch.cat(weights1)
    bias_vec=torch.cat(bias1)
    #print('weights vector')
    #print(weights_vec)
    #print('bias vector')
    return weights1, weights_vec, bias_vec

In [ ]:
weights1, weights_vec, bias_vec = get_wb(model)

Weight matrix for rnn.encoding_layer.weight:
Parameter containing:
tensor([[-1.5405, -0.3515, -0.3186,  ...,  0.6964,  1.0487, -0.4811],
        [ 0.8839, -0.1836, -0.0400,  ...,  0.5956, -0.0908,  0.0568],
        [ 0.0724, -0.8025,  0.7511,  ...,  0.9484, -1.0034, -1.4723],
        ...,
        [ 1.0028,  0.0467, -0.6503,  ..., -0.5072, -0.6748,  1.6817],
        [ 1.0575, -0.2266,  0.2583,  ...,  0.2257, -0.0640,  0.3134],
        [-0.4202,  0.1140, -0.7010,  ...,  0.8381,  2.6865,  2.0627]],
       device='cuda:0', requires_grad=True)
Weight matrix for rnn.LayerNorm.weight:
Parameter containing:
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
Bias vector for rnn.LayerNorm.bias:
Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', requires_grad=True)
Weight matrix for rnn.transformer_encoder.layers.0.self_attn.in_proj_weight:
Parameter containing:
tensor([[-0.0259,  0.0252, -0.0164,  ...,  0.0188, -0.0027,  0.0262],
        [-0.00

Binarizacija

In [ ]:
#Binarizacija
novi_param = []
poz = []
for i in range(len(weights1)):
  if int(weights1[i].numel()) >1000000:
    print(weights1[i].size)
    novi = torch.where(weights1[i] > 0, torch.tensor(1), torch.tensor(-1))
    a = novi.cpu()
    novi_np = a.detach().numpy()

    novi_np = np.asarray(novi_np).astype(np.float32)
    print(novi_np.shape)
    #novi = np.asarray(novi).astype(np.float32)
    print(novi_np)
    #print(int(novi_np.numel()))
    poz.append(i)
    novi_param.append(novi_np)

<built-in method size of Tensor object at 0x7cd1d31309f0>
(5713200,)
[-1.  1. -1. ...  1.  1. -1.]
<built-in method size of Tensor object at 0x7cd1d310fd80>
(1904400,)
[-1. -1. -1. ...  1. -1. -1.]
<built-in method size of Tensor object at 0x7cd1d3130630>
(2826240,)
[-1.  1.  1. ... -1.  1.  1.]
<built-in method size of Tensor object at 0x7cd1d31301d0>
(2826240,)
[ 1. -1.  1. ... -1.  1.  1.]
<built-in method size of Tensor object at 0x7cd1d3130180>
(5713200,)
[-1.  1. -1. ...  1.  1. -1.]
<built-in method size of Tensor object at 0x7cd1d3130220>
(1904400,)
[-1. -1. -1. ...  1. -1. -1.]
<built-in method size of Tensor object at 0x7cd1d31300e0>
(2826240,)
[-1.  1.  1. ... -1.  1.  1.]
<built-in method size of Tensor object at 0x7cd1d30d9ee0>
(2826240,)
[ 1. -1.  1. ... -1.  1.  1.]


In [ ]:
i=0
with torch.no_grad():
  for name, params in model.named_parameters():
    print(name)
    print(params.shape)
    if 'weight' in name:
      if params.numel()>1000000:
        print(i)
        velicina = params.shape
        novi_param[i] = np.asarray(novi_param[i]).astype(np.float32)
        print(novi_param[i].dtype)
        novi_reshaped = np.reshape(novi_param[i], velicina)
        params.data.copy_(torch.from_numpy(novi_reshaped))
        i=i+1

rnn.encoding_layer.weight
torch.Size([110, 1380])
rnn.LayerNorm.weight
torch.Size([1380])
rnn.LayerNorm.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.self_attn.in_proj_weight
torch.Size([4140, 1380])
0
float32
rnn.transformer_encoder.layers.0.self_attn.in_proj_bias
torch.Size([4140])
rnn.transformer_encoder.layers.0.self_attn.out_proj.weight
torch.Size([1380, 1380])
1
float32
rnn.transformer_encoder.layers.0.self_attn.out_proj.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.linear1.weight
torch.Size([2048, 1380])
2
float32
rnn.transformer_encoder.layers.0.linear1.bias
torch.Size([2048])
rnn.transformer_encoder.layers.0.linear2.weight
torch.Size([1380, 2048])
3
float32
rnn.transformer_encoder.layers.0.linear2.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm1.weight
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm1.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm2.weight
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm2.bias
t

FP8

In [ ]:
def FP8_v2(input_data):
  sgn_len=1
  exp_len=5
  mant_len=2

  if input_data >=  0:
    s = 0
  else:
    #s = - 1 # proveriti i ovu varijantu ako postoji neslaganje
    s = 1

  Eb = np.floor(np.log2(np.abs(input_data)))

  if Eb > 2 ** (exp_len - 1) - 1:
    Eb = 2 ** (exp_len - 1)

  if Eb < - 2 ** (exp_len - 1):
    Eb = - 2 ** (exp_len - 1)

  #M = np.round((2 ** (mant_len)) * ((np.abs(input_data)/Eb) - 1)) # ovde je bila greska u tekstu izgleda, tj. treba deliti sa 2^Eb umesto sa Eb.
  M = np.round((2 ** (mant_len)) * (np.abs(input_data)/(2 ** (Eb)) - 1))

  if M > (2 ** (mant_len)) - 1:
    M = (2 ** (mant_len)) - 1

  if M < 0:
    M = 0

  Quantized_data = ((-1)**s) * (2 ** Eb) * (1 + M / (2 ** (mant_len)))

  return Quantized_data

In [ ]:
t = []
for i in range(len(weights1[2])):
  x = weights1[2][i]

  a = x.cpu()
  y = a.detach().numpy()

  x1 = FP8_v2(y)
  t.append(x1)

In [ ]:
print(y)

-0.010036595


In [ ]:
print(t)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:

print(t.shape)

AttributeError: ignored

In [ ]:
t = torch.tensor(t)

TypeError: ignored

In [ ]:

with torch.no_grad():
  for name, params in model.named_parameters():
    print(name)
    print(params.shape)
    if name == 'rnn.transformer_encoder.layers.0.self_attn.in_proj_weight':
        velicina = params.shape
        novi_param = np.asarray(t).astype(np.float32)
        print(novi_param.dtype)
        novi_reshaped = np.reshape(novi_param, velicina)
        params.data.copy_(torch.from_numpy(novi_reshaped))


rnn.encoding_layer.weight
torch.Size([110, 1380])
rnn.LayerNorm.weight
torch.Size([1380])
rnn.LayerNorm.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.self_attn.in_proj_weight
torch.Size([4140, 1380])
float32
rnn.transformer_encoder.layers.0.self_attn.in_proj_bias
torch.Size([4140])
rnn.transformer_encoder.layers.0.self_attn.out_proj.weight
torch.Size([1380, 1380])
rnn.transformer_encoder.layers.0.self_attn.out_proj.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.linear1.weight
torch.Size([2048, 1380])
rnn.transformer_encoder.layers.0.linear1.bias
torch.Size([2048])
rnn.transformer_encoder.layers.0.linear2.weight
torch.Size([1380, 2048])
rnn.transformer_encoder.layers.0.linear2.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm1.weight
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm1.bias
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm2.weight
torch.Size([1380])
rnn.transformer_encoder.layers.0.norm2.bias
torch.Size([1380])
rnn.transforme

In [ ]:
novi_np = []
novi_param=[]

for i in range(len(weights1)):
  if int(weights1[i].numel()) >1000000:
    print(weights1[i].size)
    novi =[]
    print(novi)
    for j in range(len(weights1[i])):
      input_data_t = weights1[i][j]
      a = input_data_t.cpu()
      input_data = a.detach().numpy()
      x = FP8_v2(input_data)
      #x1 = np.asarray(x).astype(np.float32)
      novi.append(x)
    novi_np = novi
    #novi_np = np.asarray(novi_np).astype(np.float32)
    #print(int(novi_np.numel()))
    poz.append(i)
    novi_param.append(novi_np)

<built-in method size of Tensor object at 0x7b03a99ae390>
[]
<built-in method size of Tensor object at 0x7b03a99adee0>
[]


AttributeError: ignored

In [ ]:
for name, params in model.named_parameters():
  print(name)
  print(params)

rnn.encoding_layer.weight
Parameter containing:
tensor([[-1.5405, -0.3515, -0.3186,  ...,  0.6964,  1.0487, -0.4811],
        [ 0.8839, -0.1836, -0.0400,  ...,  0.5956, -0.0908,  0.0568],
        [ 0.0724, -0.8025,  0.7511,  ...,  0.9484, -1.0034, -1.4723],
        ...,
        [ 1.0028,  0.0467, -0.6503,  ..., -0.5072, -0.6748,  1.6817],
        [ 1.0575, -0.2266,  0.2583,  ...,  0.2257, -0.0640,  0.3134],
        [-0.4202,  0.1140, -0.7010,  ...,  0.8381,  2.6865,  2.0627]],
       device='cuda:0', requires_grad=True)
rnn.LayerNorm.weight
Parameter containing:
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
rnn.LayerNorm.bias
Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', requires_grad=True)
rnn.transformer_encoder.layers.0.self_attn.in_proj_weight
Parameter containing:
tensor([[-0.0273,  0.0234, -0.0156,  ...,  0.0195, -0.0024,  0.0273],
        [-0.0068,  0.0117, -0.0273,  ..., -0.0024,  0.0039,  0.0156],
        [-0.0312, 

In [ ]:
torch.save(model, '/content/drive/MyDrive/Master_2023_sept/COGMEN-main/milion_model1.pt')

In [ ]:
model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/milion_model1.pt')

Evaluacija modela

In [ ]:
#!python preprocess.py --dataset="iemocap_4"

Seed set
train: 100% 108/108 [00:13<00:00,  8.19it/s]
dev: 100% 12/12 [00:00<00:00, 25.59it/s]
test: 100% 31/31 [00:01<00:00, 25.68it/s]
11/11/2023 05:00:25 train vids:
11/11/2023 05:00:25 ['Ses01F_impro01', 'Ses01F_impro02', 'Ses01F_impro04', 'Ses01F_impro05', 'Ses01F_impro06', 'Ses01F_impro07', 'Ses01F_script01_1', 'Ses01F_script01_2', 'Ses01F_script01_3', 'Ses01F_script02_1', 'Ses01F_script03_1', 'Ses01F_script03_2', 'Ses01M_impro01', 'Ses01M_impro02', 'Ses01M_impro03', 'Ses01M_impro04', 'Ses01M_impro06', 'Ses01M_impro07', 'Ses01M_script01_1', 'Ses01M_script01_2', 'Ses01M_script01_3', 'Ses01M_script02_1', 'Ses01M_script02_2', 'Ses01M_script03_1', 'Ses01M_script03_2', 'Ses02F_impro01', 'Ses02F_impro02', 'Ses02F_impro03', 'Ses02F_impro04', 'Ses02F_impro06', 'Ses02F_impro07', 'Ses02F_impro08', 'Ses02F_script01_2', 'Ses02F_script02_1', 'Ses02F_script02_2', 'Ses02F_script03_1', 'Ses02F_script03_2', 'Ses02M_impro01', 'Ses02M_impro02', 'Ses02M_impro03', 'Ses02M_impro04', 'Ses02M_impro05', 

In [ ]:
#!python train.py --dataset="iemocap_4" --modalities="atv" --from_begin --epochs=55

2023-11-11 17:01:36.985536: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-11 17:01:36.985599: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-11 17:01:36.985643: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-11-11 17:01:38.829814: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Seed set
11/11/2023 05:01:40 Loaded data.
SeqContext-> USING Transformer
args.drop_rate: 0.5
bn
<generator object Module.parameters at 0x7c94d9315b60>
gnn_nheads
1
Using Scheduler
11/11/2023 05:01:47 Start training...
Help on Coach in mod

In [ ]:
!python eval.py --dataset="iemocap_4" --modalities="atv"

Namespace(dataset='iemocap_4', transformers=False, data_dir_path='./data', from_begin=True, model_ckpt=None, device='cuda', epochs=55, batch_size=32, optimizer='adam', scheduler='reduceLR', learning_rate=0.0001, weight_decay=1e-08, max_grad_value=-1, drop_rate=0.5, wp=5, wf=5, n_speakers=2, hidden_size=100, rnn='transformer', class_weight=False, encoding=None, trans_encoding=False, modalities='atv', emotion=None, concat_gin_gout=False, seqcontext_nlayer=2, gnn_nheads=1, num_bases=7, use_highway=False, seed=24, log_in_comet=False, comet_api_key=None, comet_workspace=None, use_pe_in_seqcontext=False, tuning=False, tag='hyperparameters_opt', dataset_embedding_dims={'iemocap': {'a': 100, 't': 768, 'v': 512, 'at': 868, 'tv': 1280, 'av': 612, 'atv': 1380}, 'iemocap_4': {'a': 100, 't': 768, 'v': 512, 'at': 868, 'tv': 1280, 'av': 612, 'atv': 1380}, 'mosei': {'a': 80, 't': 768, 'v': 35, 'at': 848, 'tv': 803, 'av': 115, 'atv': 883}}, data='./data/iemocap_4/data_iemocap_4.pkl')
test: 100% 1/1 [00

In [ ]:
# import pickle as pkl

# from sklearn.metrics import classification_report, confusion_matrix
# model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/new_model.pt')

# with open("/content/drive/MyDrive/Master_2023_sept/COGMEN-main/testset.pkl", "rb") as f:
#     test_dataset = pkl.load(f)
# Y_pred = model(test_dataset)

# y_pred = np.argmax(Y_pred, axis=1)

# print('                     ')
# print('Confusion Matrix')
# print('                     ')
# print(confusion_matrix(test_dataset.classes, y_pred))
# print('------------------------------------------------')
# print('Classification Report')
# print('                     ')
# target_names = ['0', '1', '2','3']
# print(classification_report(test_dataset.classes, y_pred, target_names=target_names))

In [ ]:
import pickle as pkl
from sklearn import metrics
with open("/content/drive/MyDrive/Master_2023_sept/COGMEN-main/testset.pkl", "rb") as f:
    testset = pkl.load(f)

from tqdm import tqdm
test = True
with torch.no_grad():
    golds = []
    preds = []
    for idx in tqdm(range(len(testset)), desc="test" if test else "dev"):
        data = testset[idx]
        golds.append(data["label_tensor"])
        for k, v in data.items():
            if not k == "utterance_texts":
                data[k] = v.to('cuda')
        y_hat = model(data)
        preds.append(y_hat.detach().to("cpu"))


        golds = torch.cat(golds, dim=-1).numpy()
        preds = torch.cat(preds, dim=-1).numpy()
        f1 = metrics.f1_score(golds, preds, average="weighted")

    if test:
        print(metrics.classification_report(golds, preds, digits=4))

        # if stored_args.dataset == "mosei" and stored_args.emotion == "multilabel":
        #     happy = metrics.f1_score(golds[:, 0], preds[:, 0], average="weighted")
        #     sad = metrics.f1_score(golds[:, 1], preds[:, 1], average="weighted")
        #     anger = metrics.f1_score(golds[:, 2], preds[:, 2], average="weighted")
        #     surprise = metrics.f1_score(
        #         golds[:, 3], preds[:, 3], average="weighted"
        #     )
        #     disgust = metrics.f1_score(golds[:, 4], preds[:, 4], average="weighted")
        #     fear = metrics.f1_score(golds[:, 5], preds[:, 5], average="weighted")

        #     f1 = {
        #         "happy": happy,
        #         "sad": sad,
        #         "anger": anger,
        #         "surprise": surprise,
        #         "disgust": disgust,
        #         "fear": fear,
        #     }

        print(f"F1 Score: {f1}")


test: 100%|██████████| 1/1 [00:03<00:00,  3.61s/it]

              precision    recall  f1-score   support

           0     0.1351    0.0347    0.0552       144
           1     0.2481    0.6653    0.3614       245
           2     0.2267    0.0443    0.0741       384
           3     0.1839    0.1882    0.1860       170

    accuracy                         0.2301       943
   macro avg     0.1985    0.2331    0.1692       943
weighted avg     0.2105    0.2301    0.1660       943

F1 Score: 0.16604011067499025
