In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/Master_2023_sept/COGMEN-main

/content/drive/MyDrive/Master_2023_sept/COGMEN-main


In [3]:

!pip3 install torch torchvision #--use-deprecated=legacy-resolver
!pip3 install torchaudio #--use-deprecated=legacy-resolver
!pip3 install torch_geometric #--use-deprecated=legacy-resolver
!pip3 install comet_ml #--upgrade --quiet --use-deprecated=legacy-resolver
!pip3 install -U sentence-transformers #--use-deprecated=legacy-resolver

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 38.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 687.3/687.3 kB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 979.1/979.1 kB 48.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 76.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 26.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.9/137.9 kB 13.3 MB/s eta 0:00:00
  Attempting uninstall: python-box
    Found existing installation: python-box 7.2.0
    Uninstalling python-box-7.2.0:
      Successfully uninstalled python-box-7.2.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 8.2 MB/s eta 0:00:00


In [4]:
import torch
import torch.nn as nn
import numpy as np

In [ ]:
!python preprocess.py --dataset="iemocap_4"

Seed set
train: 100% 108/108 [00:12<00:00,  8.82it/s]
dev: 100% 12/12 [00:00<00:00, 25.19it/s]
test: 100% 31/31 [00:01<00:00, 24.45it/s]
11/02/2023 11:43:15 train vids:
11/02/2023 11:43:15 ['Ses01F_impro01', 'Ses01F_impro02', 'Ses01F_impro04', 'Ses01F_impro05', 'Ses01F_impro06', 'Ses01F_impro07', 'Ses01F_script01_1', 'Ses01F_script01_2', 'Ses01F_script01_3', 'Ses01F_script02_1', 'Ses01F_script03_1', 'Ses01F_script03_2', 'Ses01M_impro01', 'Ses01M_impro02', 'Ses01M_impro03', 'Ses01M_impro04', 'Ses01M_impro06', 'Ses01M_impro07', 'Ses01M_script01_1', 'Ses01M_script01_2', 'Ses01M_script01_3', 'Ses01M_script02_1', 'Ses01M_script02_2', 'Ses01M_script03_1', 'Ses01M_script03_2', 'Ses02F_impro01', 'Ses02F_impro02', 'Ses02F_impro03', 'Ses02F_impro04', 'Ses02F_impro06', 'Ses02F_impro07', 'Ses02F_impro08', 'Ses02F_script01_2', 'Ses02F_script02_1', 'Ses02F_script02_2', 'Ses02F_script03_1', 'Ses02F_script03_2', 'Ses02M_impro01', 'Ses02M_impro02', 'Ses02M_impro03', 'Ses02M_impro04', 'Ses02M_impro05', 

In [ ]:
!python train.py --dataset="iemocap_4" --modalities="atv" --from_begin --epochs=55

2023-10-31 09:20:40.029595: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-10-31 09:20:40.029668: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-10-31 09:20:40.029716: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-10-31 09:20:41.099111: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Seed set
10/31/2023 09:20:42 Loaded data.
SeqContext-> USING Transformer
args.drop_rate: 0.5
bn
<generator object Module.parameters at 0x78503685c510>
gnn_nheads
1
Using Scheduler
10/31/2023 09:20:46 Start training...
Help on Coach in mod

In [ ]:
!python eval.py --dataset="iemocap_4" --modalities="atv"

test: 100% 1/1 [00:01<00:00,  1.12s/it]
              precision    recall  f1-score   support

           0     0.7517    0.7778    0.7645       144
           1     0.8783    0.8245    0.8505       245
           2     0.8234    0.7891    0.8059       384
           3     0.7755    0.8941    0.8306       170

    accuracy                         0.8155       943
   macro avg     0.8072    0.8214    0.8129       943
weighted avg     0.8181    0.8155    0.8156       943

F1 Score: 0.8156062342235146


In [5]:
model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/trained_model3.pt')

<ipython-input-5-abc098b37b9e>:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/trained_model3.pt')
/

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.78k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/718 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.32k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

ModuleNotFoundError: No module named 'torch_geometric.nn.conv.utils.inspector'

In [ ]:
weights1=[]
bias1=[]
def get_wb(model):
    for name, param in model.named_parameters():
        if 'weight' in name:
            print(f'Weight matrix for {name}:')
            print(param)
            weights1.append(param.view(-1))
        elif 'bias' in name:
            print(f'Bias vector for {name}:')
            print(param)
            bias1.append(param.view(-1))
    # print(weights_and_biases_vector)
    weights_vec=torch.cat(weights1)
    bias_vec=torch.cat(bias1)
    #print('weights vector')
    #print(weights_vec)
    #print('bias vector')
    return weights1, weights_vec, bias_vec

In [ ]:
weights1, weights_vec, bias_vec = get_wb(model)

Weight matrix for rnn.encoding_layer.weight:
Parameter containing:
tensor([[-1.5405, -0.3515, -0.3186,  ...,  0.6964,  1.0487, -0.4811],
        [ 0.8839, -0.1836, -0.0400,  ...,  0.5956, -0.0908,  0.0568],
        [ 0.0724, -0.8025,  0.7511,  ...,  0.9484, -1.0034, -1.4723],
        ...,
        [ 1.0028,  0.0467, -0.6503,  ..., -0.5072, -0.6748,  1.6817],
        [ 1.0575, -0.2266,  0.2583,  ...,  0.2257, -0.0640,  0.3134],
        [-0.4202,  0.1140, -0.7010,  ...,  0.8381,  2.6865,  2.0627]],
       device='cuda:0', requires_grad=True)
Weight matrix for rnn.LayerNorm.weight:
Parameter containing:
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
Bias vector for rnn.LayerNorm.bias:
Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', requires_grad=True)
Weight matrix for rnn.transformer_encoder.layers.0.self_attn.in_proj_weight:
Parameter containing:
tensor([[-0.0259,  0.0252, -0.0164,  ...,  0.0188, -0.0027,  0.0262],
        [-0.00

In [ ]:
novi_param = []
poz = []
for i in range(len(weights1)):
    print(weights1[i].size)
    novi = torch.where(weights1[i] > 0, torch.tensor(1), torch.tensor(-1))
    a = novi.cpu()
    novi_np = a.detach().numpy()

    novi_np = np.asarray(novi_np).astype(np.float32)
    print(novi_np.shape)
    #novi = np.asarray(novi).astype(np.float32)
    print(novi_np)
    #print(int(novi_np.numel()))
    poz.append(i)
    novi_param.append(novi_np)

<built-in method size of Tensor object at 0x7efd4017be70>
(151800,)
[-1. -1. -1. ...  1.  1.  1.]
<built-in method size of Tensor object at 0x7efd40148b30>
(1380,)
[1. 1. 1. ... 1. 1. 1.]
<built-in method size of Tensor object at 0x7efd40194a40>
(5713200,)
[-1.  1. -1. ...  1.  1. -1.]
<built-in method size of Tensor object at 0x7efd401949a0>
(1904400,)
[-1. -1. -1. ...  1. -1. -1.]
<built-in method size of Tensor object at 0x7efd401949f0>
(2826240,)
[-1.  1.  1. ... -1.  1.  1.]
<built-in method size of Tensor object at 0x7efd401940e0>
(2826240,)
[ 1. -1.  1. ... -1.  1.  1.]
<built-in method size of Tensor object at 0x7efd40195260>
(1380,)
[1. 1. 1. ... 1. 1. 1.]
<built-in method size of Tensor object at 0x7efd401947c0>
(1380,)
[1. 1. 1. ... 1. 1. 1.]
<built-in method size of Tensor object at 0x7efd401951c0>
(5713200,)
[-1.  1. -1. ...  1.  1. -1.]
<built-in method size of Tensor object at 0x7efd40194130>
(1904400,)
[-1. -1. -1. ...  1. -1. -1.]
<built-in method size of Tensor object

In [ ]:
i=0
with torch.no_grad():
  for name, params in model.named_parameters():
    if 'weight' in name:
      print(name)
      print(params.shape)

      print(i)
      velicina = params.shape
      novi_param[i] = np.asarray(novi_param[i]).astype(np.float32)
      print(novi_param[i].dtype)
      novi_reshaped = np.reshape(novi_param[i], velicina)
      params.data.copy_(torch.from_numpy(novi_reshaped))
      i=i+1

rnn.encoding_layer.weight
torch.Size([110, 1380])
0
float32
rnn.LayerNorm.weight
torch.Size([1380])
1
float32
rnn.transformer_encoder.layers.0.self_attn.in_proj_weight
torch.Size([4140, 1380])
2
float32
rnn.transformer_encoder.layers.0.self_attn.out_proj.weight
torch.Size([1380, 1380])
3
float32
rnn.transformer_encoder.layers.0.linear1.weight
torch.Size([2048, 1380])
4
float32
rnn.transformer_encoder.layers.0.linear2.weight
torch.Size([1380, 2048])
5
float32
rnn.transformer_encoder.layers.0.norm1.weight
torch.Size([1380])
6
float32
rnn.transformer_encoder.layers.0.norm2.weight
torch.Size([1380])
7
float32
rnn.transformer_encoder.layers.1.self_attn.in_proj_weight
torch.Size([4140, 1380])
8
float32
rnn.transformer_encoder.layers.1.self_attn.out_proj.weight
torch.Size([1380, 1380])
9
float32
rnn.transformer_encoder.layers.1.linear1.weight
torch.Size([2048, 1380])
10
float32
rnn.transformer_encoder.layers.1.linear2.weight
torch.Size([1380, 2048])
11
float32
rnn.transformer_encoder.layers.1

In [ ]:
for name, params in model.named_parameters():
  print(name)
  print(params)

rnn.encoding_layer.weight
Parameter containing:
tensor([[-1., -1., -1.,  ...,  1.,  1., -1.],
        [ 1., -1., -1.,  ...,  1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  1., -1., -1.],
        ...,
        [ 1.,  1., -1.,  ..., -1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  1., -1.,  1.],
        [-1.,  1., -1.,  ...,  1.,  1.,  1.]], device='cuda:0',
       requires_grad=True)
rnn.LayerNorm.weight
Parameter containing:
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
rnn.LayerNorm.bias
Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', requires_grad=True)
rnn.transformer_encoder.layers.0.self_attn.in_proj_weight
Parameter containing:
tensor([[-1.,  1., -1.,  ...,  1., -1.,  1.],
        [-1.,  1., -1.,  ..., -1.,  1.,  1.],
        [-1.,  1., -1.,  ...,  1., -1.,  1.],
        ...,
        [ 1., -1.,  1.,  ...,  1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  1., -1.,  1.],
        [ 1.,  1., -1.,  ...,  1.,  1., -1.]], device='cuda

In [ ]:
torch.save(model, '/content/drive/MyDrive/Master_2023_sept/COGMEN-main/new_model.pt')

In [ ]:
model = torch.load('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/new_model.pt')

In [ ]:
weights1, weights_vec, bias_vec = get_wb(model)

Weight matrix for rnn.encoding_layer.weight:
Parameter containing:
tensor([[-1., -1., -1.,  ...,  1.,  1., -1.],
        [ 1., -1., -1.,  ...,  1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  1., -1., -1.],
        ...,
        [ 1.,  1., -1.,  ..., -1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  1., -1.,  1.],
        [-1.,  1., -1.,  ...,  1.,  1.,  1.]], device='cuda:0',
       requires_grad=True)
Weight matrix for rnn.LayerNorm.weight:
Parameter containing:
tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0', requires_grad=True)
Bias vector for rnn.LayerNorm.bias:
Parameter containing:
tensor([0., 0., 0.,  ..., 0., 0., 0.], device='cuda:0', requires_grad=True)
Weight matrix for rnn.transformer_encoder.layers.0.self_attn.in_proj_weight:
Parameter containing:
tensor([[-1.,  1., -1.,  ...,  1., -1.,  1.],
        [-1.,  1., -1.,  ..., -1.,  1.,  1.],
        [-1.,  1., -1.,  ...,  1., -1.,  1.],
        ...,
        [ 1., -1.,  1.,  ...,  1., -1.,  1.],
        [ 1., -1.,  1.,  ...,  

In [ ]:
!python eval.py --dataset="iemocap_4" --modalities="atv" --model='model'

test: 100% 1/1 [00:00<00:00,  1.28it/s]
              precision    recall  f1-score   support

           0     0.1905    0.0278    0.0485       144
           1     0.2637    0.7061    0.3840       245
           2     0.3784    0.1094    0.1697       384
           3     0.1419    0.1294    0.1354       170

    accuracy                         0.2556       943
   macro avg     0.2436    0.2432    0.1844       943
weighted avg     0.2773    0.2556    0.2007       943

F1 Score: 0.20068418863442186


In [ ]:
%cd /content/drive/MyDrive/Master_2023_sept/COGMEN-main

/content/drive/MyDrive/Master_2023_sept/COGMEN-main


In [ ]:
import cogmen

In [ ]:
data = cogmen.utils.load_pkl('/content/drive/MyDrive/Master_2023_sept/COGMEN-main/data/iemocap/data_iemocap.pkl')

In [ ]:
class MyClass:
    def __init__(self, args):
        self.args = args
    def pr(self):
      print(self.args)



In [ ]:
args.data = data

NameError: ignored

In [ ]:
testset = cogmen.Dataset(data["test"],**args)

TypeError: ignored

In [ ]:
import torch
test_dataset=
# Assuming you have a test_dataset
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=10, shuffle=False)

# Set the model to evaluation mode
model.eval()

correct = 0
total = 0

with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = correct / total
print(f'Test Accuracy: {accuracy * 100:.2f}%')



In [ ]:
batch_size = 8
from sklearn.metrics import classification_report, confusion_matrix

Y_pred = model.predict_generator(test_dataset, 3254 // batch_size+1)

y_pred = np.argmax(Y_pred, axis=1)

print('                     ')
print('Confusion Matrix')
print('                     ')
print(confusion_matrix(test_dataset.classes, y_pred))
print('------------------------------------------------')
print('Classification Report')
print('                     ')
target_names = ['0', '1', '2','3']
print(classification_report(test_dataset.classes, y_pred, target_names=target_names))